// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/user/UserFunction.proto

package com.demo.grpc.function.api.user;

public final class UserFunctionDescriptor {
  private UserFunctionDescriptor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserLoginReq_OrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLoginReq_)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    boolean hasParam();
    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest getParam();
    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder getParamOrBuilder();
  }
  /**
   * Protobuf type {@code UserLoginReq_}
   */
  public  static final class UserLoginReq_ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserLoginReq_)
      UserLoginReq_OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserLoginReq_.newBuilder() to construct.
    private UserLoginReq_(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserLoginReq_() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserLoginReq_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder subBuilder = null;
              if (param_ != null) {
                subBuilder = param_.toBuilder();
              }
              param_ = input.readMessage(com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(param_);
                param_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginReq__descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginReq__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.Builder.class);
    }

    public static final int PARAM_FIELD_NUMBER = 1;
    private com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest param_;
    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    public boolean hasParam() {
      return param_ != null;
    }
    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    public com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest getParam() {
      return param_ == null ? com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.getDefaultInstance() : param_;
    }
    /**
     * <code>.UserLoginRequest param = 1;</code>
     */
    public com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder getParamOrBuilder() {
      return getParam();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (param_ != null) {
        output.writeMessage(1, getParam());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (param_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getParam());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_)) {
        return super.equals(obj);
      }
      com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ other = (com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_) obj;

      boolean result = true;
      result = result && (hasParam() == other.hasParam());
      if (hasParam()) {
        result = result && getParam()
            .equals(other.getParam());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParam()) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getParam().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLoginReq_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLoginReq_)
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginReq__descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginReq__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.Builder.class);
      }

      // Construct using com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (paramBuilder_ == null) {
          param_ = null;
        } else {
          param_ = null;
          paramBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginReq__descriptor;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ getDefaultInstanceForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.getDefaultInstance();
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ build() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ buildPartial() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ result = new com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_(this);
        if (paramBuilder_ == null) {
          result.param_ = param_;
        } else {
          result.param_ = paramBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_) {
          return mergeFrom((com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ other) {
        if (other == com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_.getDefaultInstance()) return this;
        if (other.hasParam()) {
          mergeParam(other.getParam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest param_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder> paramBuilder_;
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public boolean hasParam() {
        return paramBuilder_ != null || param_ != null;
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest getParam() {
        if (paramBuilder_ == null) {
          return param_ == null ? com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.getDefaultInstance() : param_;
        } else {
          return paramBuilder_.getMessage();
        }
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public Builder setParam(com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          param_ = value;
          onChanged();
        } else {
          paramBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public Builder setParam(
          com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder builderForValue) {
        if (paramBuilder_ == null) {
          param_ = builderForValue.build();
          onChanged();
        } else {
          paramBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public Builder mergeParam(com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest value) {
        if (paramBuilder_ == null) {
          if (param_ != null) {
            param_ =
              com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.newBuilder(param_).mergeFrom(value).buildPartial();
          } else {
            param_ = value;
          }
          onChanged();
        } else {
          paramBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public Builder clearParam() {
        if (paramBuilder_ == null) {
          param_ = null;
          onChanged();
        } else {
          param_ = null;
          paramBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder getParamBuilder() {
        
        onChanged();
        return getParamFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      public com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder getParamOrBuilder() {
        if (paramBuilder_ != null) {
          return paramBuilder_.getMessageOrBuilder();
        } else {
          return param_ == null ?
              com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.getDefaultInstance() : param_;
        }
      }
      /**
       * <code>.UserLoginRequest param = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder> 
          getParamFieldBuilder() {
        if (paramBuilder_ == null) {
          paramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequest.Builder, com.demo.grpc.function.model.user.UserLoginRequestModel.UserLoginRequestOrBuilder>(
                  getParam(),
                  getParentForChildren(),
                  isClean());
          param_ = null;
        }
        return paramBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserLoginReq_)
    }

    // @@protoc_insertion_point(class_scope:UserLoginReq_)
    private static final com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_();
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginReq_>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginReq_>() {
      public UserLoginReq_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserLoginReq_(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginReq_> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginReq_> getParserForType() {
      return PARSER;
    }

    public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginReq_ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserLoginRes_OrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLoginRes_)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string errorCode = 1;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>string errorCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();
  }
  /**
   * Protobuf type {@code UserLoginRes_}
   */
  public  static final class UserLoginRes_ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserLoginRes_)
      UserLoginRes_OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserLoginRes_.newBuilder() to construct.
    private UserLoginRes_(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserLoginRes_() {
      errorCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserLoginRes_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginRes__descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginRes__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>string errorCode = 1;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <code>string errorCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_)) {
        return super.equals(obj);
      }
      com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ other = (com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_) obj;

      boolean result = true;
      result = result && getErrorCode()
          .equals(other.getErrorCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLoginRes_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLoginRes_)
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginRes__descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginRes__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.Builder.class);
      }

      // Construct using com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_UserLoginRes__descriptor;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ getDefaultInstanceForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.getDefaultInstance();
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ build() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ buildPartial() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ result = new com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_(this);
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_) {
          return mergeFrom((com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ other) {
        if (other == com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_.getDefaultInstance()) return this;
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object errorCode_ = "";
      /**
       * <code>string errorCode = 1;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserLoginRes_)
    }

    // @@protoc_insertion_point(class_scope:UserLoginRes_)
    private static final com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_();
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginRes_>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginRes_>() {
      public UserLoginRes_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserLoginRes_(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginRes_> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginRes_> getParserForType() {
      return PARSER;
    }

    public com.demo.grpc.function.api.user.UserFunctionDescriptor.UserLoginRes_ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetUserInfoByIdReq_OrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetUserInfoByIdReq_)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code GetUserInfoByIdReq_}
   */
  public  static final class GetUserInfoByIdReq_ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetUserInfoByIdReq_)
      GetUserInfoByIdReq_OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUserInfoByIdReq_.newBuilder() to construct.
    private GetUserInfoByIdReq_(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUserInfoByIdReq_() {
      id_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetUserInfoByIdReq_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdReq__descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdReq__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_)) {
        return super.equals(obj);
      }
      com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ other = (com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetUserInfoByIdReq_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetUserInfoByIdReq_)
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdReq__descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdReq__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.Builder.class);
      }

      // Construct using com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdReq__descriptor;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ getDefaultInstanceForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.getDefaultInstance();
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ build() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ buildPartial() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ result = new com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_) {
          return mergeFrom((com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ other) {
        if (other == com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetUserInfoByIdReq_)
    }

    // @@protoc_insertion_point(class_scope:GetUserInfoByIdReq_)
    private static final com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_();
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserInfoByIdReq_>
        PARSER = new com.google.protobuf.AbstractParser<GetUserInfoByIdReq_>() {
      public GetUserInfoByIdReq_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetUserInfoByIdReq_(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetUserInfoByIdReq_> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserInfoByIdReq_> getParserForType() {
      return PARSER;
    }

    public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdReq_ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetUserInfoByIdRes_OrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetUserInfoByIdRes_)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string errorCode = 1;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>string errorCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo> 
        getDataList();
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    com.demo.grpc.function.model.user.UserInfoModel.UserInfo getData(int index);
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    java.util.List<? extends com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetUserInfoByIdRes_}
   */
  public  static final class GetUserInfoByIdRes_ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetUserInfoByIdRes_)
      GetUserInfoByIdRes_OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUserInfoByIdRes_.newBuilder() to construct.
    private GetUserInfoByIdRes_(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUserInfoByIdRes_() {
      errorCode_ = "";
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetUserInfoByIdRes_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<com.demo.grpc.function.model.user.UserInfoModel.UserInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(
                  input.readMessage(com.demo.grpc.function.model.user.UserInfoModel.UserInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdRes__descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdRes__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>string errorCode = 1;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <code>string errorCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo> data_;
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    public java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    public java.util.List<? extends com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    public com.demo.grpc.function.model.user.UserInfoModel.UserInfo getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .UserInfo data = 2;</code>
     */
    public com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_)) {
        return super.equals(obj);
      }
      com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ other = (com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_) obj;

      boolean result = true;
      result = result && getErrorCode()
          .equals(other.getErrorCode());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetUserInfoByIdRes_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetUserInfoByIdRes_)
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdRes__descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdRes__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.class, com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.Builder.class);
      }

      // Construct using com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = "";

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.internal_static_GetUserInfoByIdRes__descriptor;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ getDefaultInstanceForType() {
        return com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.getDefaultInstance();
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ build() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ buildPartial() {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ result = new com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.errorCode_ = errorCode_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_) {
          return mergeFrom((com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ other) {
        if (other == com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_.getDefaultInstance()) return this;
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorCode_ = "";
      /**
       * <code>string errorCode = 1;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>string errorCode = 1;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<com.demo.grpc.function.model.user.UserInfoModel.UserInfo>(data_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.grpc.function.model.user.UserInfoModel.UserInfo, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder, com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder> dataBuilder_;

      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public com.demo.grpc.function.model.user.UserInfoModel.UserInfo getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder setData(
          int index, com.demo.grpc.function.model.user.UserInfoModel.UserInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder setData(
          int index, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder addData(com.demo.grpc.function.model.user.UserInfoModel.UserInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder addData(
          int index, com.demo.grpc.function.model.user.UserInfoModel.UserInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder addData(
          com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder addData(
          int index, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.demo.grpc.function.model.user.UserInfoModel.UserInfo> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public java.util.List<? extends com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.demo.grpc.function.model.user.UserInfoModel.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .UserInfo data = 2;</code>
       */
      public java.util.List<com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.demo.grpc.function.model.user.UserInfoModel.UserInfo, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder, com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.grpc.function.model.user.UserInfoModel.UserInfo, com.demo.grpc.function.model.user.UserInfoModel.UserInfo.Builder, com.demo.grpc.function.model.user.UserInfoModel.UserInfoOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetUserInfoByIdRes_)
    }

    // @@protoc_insertion_point(class_scope:GetUserInfoByIdRes_)
    private static final com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_();
    }

    public static com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserInfoByIdRes_>
        PARSER = new com.google.protobuf.AbstractParser<GetUserInfoByIdRes_>() {
      public GetUserInfoByIdRes_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetUserInfoByIdRes_(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetUserInfoByIdRes_> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserInfoByIdRes_> getParserForType() {
      return PARSER;
    }

    public com.demo.grpc.function.api.user.UserFunctionDescriptor.GetUserInfoByIdRes_ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginReq__descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserLoginReq__fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginRes__descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserLoginRes__fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserInfoByIdReq__descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserInfoByIdReq__fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserInfoByIdRes__descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserInfoByIdRes__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033api/user/UserFunction.proto\032!model/use" +
      "r/UserLoginRequest.proto\032\031model/user/Use" +
      "rInfo.proto\032\033google/protobuf/empty.proto" +
      "\"1\n\rUserLoginReq_\022 \n\005param\030\001 \001(\0132\021.UserL" +
      "oginRequest\"\"\n\rUserLoginRes_\022\021\n\terrorCod" +
      "e\030\001 \001(\t\"!\n\023GetUserInfoByIdReq_\022\n\n\002id\030\001 \001" +
      "(\004\"A\n\023GetUserInfoByIdRes_\022\021\n\terrorCode\030\001" +
      " \001(\t\022\027\n\004data\030\002 \003(\0132\t.UserInfo2z\n\014UserFun" +
      "ction\022+\n\tuserLogin\022\016.UserLoginReq_\032\016.Use" +
      "rLoginRes_\022=\n\017getUserInfoById\022\024.GetUserI" +
      "nfoByIdReq_\032\024.GetUserInfoByIdRes_B;\n\037com" +
      ".demo.grpc.function.api.userB\026UserFuncti" +
      "onDescriptorP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.grpc.function.model.user.UserLoginRequestModel.getDescriptor(),
          com.demo.grpc.function.model.user.UserInfoModel.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_UserLoginReq__descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserLoginReq__fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserLoginReq__descriptor,
        new java.lang.String[] { "Param", });
    internal_static_UserLoginRes__descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLoginRes__fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserLoginRes__descriptor,
        new java.lang.String[] { "ErrorCode", });
    internal_static_GetUserInfoByIdReq__descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetUserInfoByIdReq__fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserInfoByIdReq__descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetUserInfoByIdRes__descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetUserInfoByIdRes__fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserInfoByIdRes__descriptor,
        new java.lang.String[] { "ErrorCode", "Data", });
    com.demo.grpc.function.model.user.UserLoginRequestModel.getDescriptor();
    com.demo.grpc.function.model.user.UserInfoModel.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
